In [98]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [99]:
raw_df = pd.read_csv('lol2021.csv')
raw_df.sort_values('Team')

,Team,Player,Opponent,Position,Champion,Kills,Deaths,Assists,Creep Score,Gold Earned,Champion Damage Share,Kill Participation,Wards Placed,Wards Destroyed,Ward Interactions,Dragons For,Dragons Against,Barons For,Barons Against,Result
219,BYG,Kino,UOL,Support,Rakan,0,5,9,41,9304,0.06,0.47,49,15,64,4,1,1,1,W
23,BYG,Husha,GS,Jungle,Xin Zhao,3,3,2,177,10050,0.20,0.56,13,16,29,3,2,0,1,L
177,BYG,Doggo,DFM,Adc,Ezreal,1,1,2,351,13003,0.47,0.75,16,13,29,1,3,0,1,L
25,BYG,Maoan,GS,Mid,Orianna,2,4,3,287,12444,0.16,0.56,18,7,25,3,2,0,1,L
27,BYG,Doggo,GS,Adc,Ezreal,3,2,1,382,14682,0.41,0.44,14,8,22,3,2,0,1,L
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,UOL,Argonavt,C9,Adc,Senna,2,0,16,50,8808,0.22,0.95,22,7,29,3,1,0,0,W
169,UOL,Santas,C9,Support,Sion,2,1,9,184,8889,0.09,0.58,11,7,18,3,1,0,0,W
34,UOL,Nomanz,DFM,Mid,Orianna,1,6,4,294,12248,0.35,0.71,14,5,19,1,4,0,2,L
93,UOL,Ahahacik,BYG,Jungle,Lee Sin,0,4,3,143,7165,0.14,0.43,9,5,14,1,1,0,1,L
0,UOL,Boss,GS,Top,Camille,4,5,3,188,11107,0.17,0.78,8,8,16,0,4,0,1,L

Tenemos un Data set con resultados de la liga de League of Legends 2021. Incluye distinos datos, tanto categÃ³ricos como numÃ©ricos.

In [100]:
raw_df.sort_values('Player')

,Team,Player,Opponent,Position,Champion,Kills,Deaths,Assists,Creep Score,Gold Earned,Champion Damage Share,Kill Participation,Wards Placed,Wards Destroyed,Ward Interactions,Dragons For,Dragons Against,Barons For,Barons Against,Result
49,INF,Ackerman,HLE,Support,Amumu,0,3,4,35,6137,0.06,0.50,47,12,59,1,3,0,1,L
138,INF,Ackerman,PCE,Support,Rakan,0,2,12,51,7715,0.08,0.71,62,21,83,0,4,0,1,L
68,INF,Ackerman,RED,Support,Nami,0,2,5,21,6744,0.09,0.83,43,18,61,3,2,0,1,L
199,INF,Ackerman,LNG,Support,Braum,0,3,1,28,4714,0.10,0.33,39,6,45,1,2,0,0,L
183,RED,Aegis,PCE,Jungle,Graves,4,5,4,176,10388,0.22,0.89,11,9,20,2,2,1,0,L
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17,C9,Zven,DFM,Adc,Miss Fortune,3,0,6,299,13145,0.22,0.69,13,9,22,4,0,1,0,W
207,C9,Zven,DFM,Adc,Miss Fortune,2,4,3,372,14765,0.14,0.42,12,20,32,4,2,0,2,L
166,C9,Zven,UOL,Adc,Miss Fortune,2,3,4,236,9735,0.20,0.55,10,3,13,1,3,0,0,L
117,C9,Zven,BYG,Adc,Ezreal,9,1,5,390,19588,0.33,0.54,15,10,25,4,1,2,0,W
86,C9,Zven,GS,Adc,Ezreal,6,1,12,267,14154,0.37,0.82,12,7,19,2,2,1,0,W

In [101]:
ss = StandardScaler()

Xstd = ss.fit_transform(raw_df[['Kills', 'Wards Placed']].values)
print (Xstd.mean(), Xstd.std())

5.652044489000796e-17 1.0

In [102]:
 x = raw_df[['Kills', 'Creep Score', 'Gold Earned']]
    mms = minMaxScaler()
    Xn = mms.fit_transform(x)

IndentationError: unexpected indent (<ipython-input-102-fc276509e1e8>, line 2)

In [ ]:
print (Xn.min(axis=0))
print (Xn.max(axis=0))